apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tgads-applicationset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: busybox
        namespace: busybox
        path: apps/busybox
  template:
    metadata:
      name: '{{name}}-app'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: git@github.com:esurkov1/tgads-ops.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true