# Конфигурация ArgoCD
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Настройки репозитория
  repositories: |
    - type: git
      url: git@github.com:esurkov1/tgads-ops.git
  
  # Настройки ресурсов
  resource.exclusions: |
    - apiGroups: [""]
      kinds: ["ConfigMap"]
      clusters: ["*"]
      name: "kube-root-ca.crt"
    - apiGroups: [""]
      kinds: ["ConfigMap"]
      clusters: ["*"]
      name: "argocd-cm"
  
  # Дополнительные настройки
  timeout.reconciliation: 180s
  application.instanceLabelKey: argocd.argoproj.io/instance
