apiVersion: v1
kind: Secret
metadata:
  name: tgads-repo-ssh-key
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
data:
  sshPrivateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUFzek5rNWhMV1VLUXlOVFV4T1FBQUFDRG1tMEV1Q2NkdGVSVzV1VTlSWExDRFFmY2NTV3NxcHhLK3A3WUZoaUpjRUFBQUFKZ0JveWR5ZEFhSWNLblFBQUFBdHpjMmd0WldReU5UVXhPUUFBQUNEbG0wRXVDY2R0ZVJXNXVVOVJYTENEUWZjY1NXc3FweEsrcDdZRmhpSmNFQQpBQUFFQ3A5VUtDdklkM1ZTV3BTUE9LRTFVN28zeTZ5R3cxcDhUY2wyZ2FqQ1ZFa2VXYlFTNEp4MjE1RmJtNVQxRmNzSU5CCjl4eEpheXFuRXI2bnRnV0dJbHdRQUFBQUQyVnpkWEpyYjNZeFFHZHBkR2gxWWdFQ0F3UUZCZ3M9Ci0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo=
  url: Z2l0QGdpdGh1Yi5jb206ZXN1cmtvdjEvdGdhZHMtb3BzLmdpdA==
  type: Z2l0
