apiVersion: v1
kind: Service
metadata:
  name: busybox
  namespace: busybox
  labels:
    app: busybox
spec:
  selector:
    app: busybox
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
